name: enterprise workflow

on:
  push:
    branches:
      main
  workflow_dispatch:
    input:
      description: name
      type: string
      default: "Hello, people!"
      required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello from github actions!"